name: Build Mod

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build Mod
      run: ./gradlew build

    - name: Upload JAR artifact
      uses: actions/upload-artifact@v2
      with:
        name: mod-jar
        path: build/libs/*.jar
